# Generated by Django 4.0.1 on 2022-12-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='tg_user_ud',
            new_name='tg_user_id',
        ),
    ]
